# Generated by Django 5.0.6 on 2026-05-10 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_productionorder_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'permissions': [('can_view_inventory', 'Can view inventory'), ('can_manage_stock', 'Can manage stock (stock in/out)'), ('can_manage_products', 'Can manage products (create/edit/delete)'), ('can_manage_purchase', 'Can manage purchase (POs, suppliers)'), ('can_manage_users', 'Can manage users')]},
        ),
        migrations.AlterModelOptions(
            name='productionorder',
            options={'ordering': ['-created_at', '-id'], 'permissions': [('can_manage_production', 'Can manage production (confirm/start/complete)')]},
        ),
    ]
