# Generated by Django 5.0.6 on 2026-05-10 09:53

from django.db import migrations


def setup_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    
    # Get the content types
    product_ct = ContentType.objects.get(app_label='inventory', model='product')
    po_ct = ContentType.objects.get(app_label='inventory', model='productionorder')
    
    # Define permissions mapping
    def get_perm(codename, ct):
        perm, _ = Permission.objects.get_or_create(
            codename=codename,
            content_type=ct,
            defaults={'name': codename.replace('_', ' ').capitalize()}
        )
        return perm

    perms = {
        'can_view_inventory': get_perm('can_view_inventory', product_ct),
        'can_manage_stock': get_perm('can_manage_stock', product_ct),
        'can_manage_products': get_perm('can_manage_products', product_ct),
        'can_manage_purchase': get_perm('can_manage_purchase', product_ct),
        'can_manage_users': get_perm('can_manage_users', product_ct),
        'can_manage_production': get_perm('can_manage_production', po_ct),
    }
    
    # Create Groups
    viewer_group, _ = Group.objects.get_or_create(name='Viewer')
    storekeeper_group, _ = Group.objects.get_or_create(name='Storekeeper')
    manager_group, _ = Group.objects.get_or_create(name='Manager')
    admin_group, _ = Group.objects.get_or_create(name='Admin')
    
    # Assign Permissions
    viewer_group.permissions.add(perms['can_view_inventory'])
    
    storekeeper_group.permissions.add(
        perms['can_view_inventory'],
        perms['can_manage_stock']
    )
    
    manager_group.permissions.add(
        perms['can_view_inventory'],
        perms['can_manage_stock'],
        perms['can_manage_products'],
        perms['can_manage_purchase'],
        perms['can_manage_production']
    )
    
    admin_group.permissions.add(*perms.values())

def remove_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=['Viewer', 'Storekeeper', 'Manager', 'Admin']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_product_options_alter_productionorder_options'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RunPython(setup_groups, remove_groups),
    ]
