# Generated by Django 5.0.6 on 2026-05-10 10:27

from django.db import migrations


def update_groups_with_purchase(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    
    product_ct = ContentType.objects.get(app_label='inventory', model='product')
    
    def get_perm(codename, ct):
        perm, _ = Permission.objects.get_or_create(
            codename=codename,
            content_type=ct,
            defaults={'name': codename.replace('_', ' ').capitalize()}
        )
        return perm

    can_manage_purchase = get_perm('can_manage_purchase', product_ct)
    
    # Update Manager and Admin groups
    manager_group = Group.objects.get(name='Manager')
    admin_group = Group.objects.get(name='Admin')
    
    manager_group.permissions.add(can_manage_purchase)
    admin_group.permissions.add(can_manage_purchase)

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_supplier_purchaseorder_purchaseorderitem'),
    ]

    operations = [
        migrations.RunPython(update_groups_with_purchase),
    ]
