# Generated by Django 5.0.6 on 2026-05-10 10:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Format: +countrycode_number (e.g., +14155238886)', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('low_stock_alerts', models.BooleanField(default=False)),
                ('production_updates', models.BooleanField(default=False)),
                ('purchase_approvals', models.BooleanField(default=False)),
                ('goods_received', models.BooleanField(default=False)),
                ('daily_summary', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('low_stock', 'Low Stock'), ('production', 'Production Update'), ('purchase', 'Purchase Order'), ('receipt', 'Goods Received'), ('daily', 'Daily Summary'), ('test', 'Test Message')], max_length=20)),
                ('content', models.TextField()),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='sent', max_length=20)),
                ('twilio_sid', models.CharField(blank=True, max_length=50, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='notifications.whatsapprecipient')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
